services:
  db:
    container_name: postgres-db-inspection-1
    image: postgres:15.1
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./dockerdata/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret1234!
